version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: toursafe-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: toursafedb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: toursafe-redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: toursafe-minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data:
